version: '3'
services:
        web:
                restart: always
                build: .
                ports:
                      - 80:80
                volumes:
                        - ./html:/var/www/html
                depends_on:
                        - db
        db:
                restart: always
                image: mysql:5.6
                ports:
                      - 3306:3306
                environment:
                      MYSQL_ROOT_PASSWORD: root
                      MYSQL_DATABASE: sample_db
                      MYSQL_USER: user
                      MYSQL_PASSWORD: password

        phpmyadmin:
                image: phpmyadmin/phpmyadmin
                ports:
                      - 4040:80
