version: '3'
services:
  web:
    tty: true
    privileged: true
    command: /sbin/init
    build: .
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html
    container_name: "apache-php"
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    container_name: "mysql5.7"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    container_name: "phpmyamin"
